### ISSUE TITLE
Sign incoming mail or wildcard?

### ISSUE THREAD

**Issue by lxhunter** [croessner/sigh#1]
Hi there,

i would like to also sign every E-Mail which is sent to a certain addresse or even better a certain domain. For archiving purposes. Is this already possible? 

Cheers,
Alex

**Comment by croessner** [comment]
You can add it for each address. It does (probably) not work for a domain. And I think it also should not do it for a domain, as you had a missmatch between signature and sender, because the S/MIME certifiacte is for a user and not a domain ;)

**Comment by lxhunter** [comment]
You are absolutely right about the domain matching part. Does sigh differentiate between sender and recipient?

**Comment by croessner** [comment]
It signs for senders

**Comment by lxhunter** [comment]
I believe i have read an article by you, where you talked about the usage of postfix/dovecot as a mail archive. From your idea I implemented the whole setup, just add a bcc and the mail is going to be archived. the only thing missing is that i want to sign incoming mail. In my understanding, i could not use sigh for that, as the bcced address is not the sender. Am I right? Would you have another suggestion? Would be greatly appreciated!

**Comment by croessner** [comment]
Not sure :) What I had done for some time is using smilla (SMIMEA-milter) do encrypt incoming mails to myself. But that milter does not sign. If you only want to protect against manipulation, encryption could be an option in that case. You could also use openpgpkey (there exists a milter for OpenPGP). Does that help you?

**Comment by lxhunter** [comment]
[The article was by Robert](https://sys4.de/de/blog/2013/02/07/mailarchiv-mit-dovecot-und-postfix-sortiert-nach-datum-mailadressen-und-ein-ausgehend-unterordnern/) :) I will look into the direction you pointed out. Thanks very much!!!

**Comment by croessner** [comment]
You're welcome :)
